# Generated by Django 5.0.1 on 2024-01-21 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hashtags', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
